apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          args:
            - "server"
            - "-dev"  # Запуск Vault в dev-режиме
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"  # Для тестирования, в реальной ситуации надо изменить
          volumeMounts:
            - name: vault-data
              mountPath: /vault/file
      volumes:
        - name: vault-data
          emptyDir: {}
