apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-local
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  project: default
  source:
    repoURL: https://github.com/andreytiop/helmtest.git
    targetRevision: main
    path: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
